---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radixdlt-faucet.fullname" . }}-secretmap
  labels:
    app: {{ include "radixdlt-faucet.name" . }}
    chart: {{ include "radixdlt-faucet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range $key,$value := .Values.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
