---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "radixdlt-core.fullname" . }}-envmap
  labels:
    app: {{ include "radixdlt-core.name" . }}
    chart: {{ include "radixdlt-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key,$value := .Values.environment }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
