apiVersion: v1
kind: Service
metadata:
  name: {{ include "radixdlt-core.fullname" . }}
  labels:
    {{- include "radixdlt-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.radix }}
      targetPort: radix
      protocol: UDP
      name: radix
  selector:
    {{- include "radixdlt-core.selectorLabels" . | nindent 4 }}
